
  var city = [{
    "name" : "new Orleans",
    "less" : "macon",
    "city1" : "baton Rouge",
    "city2" : "kansas City",
    "city3" : "las Vegas",
  },
  {
    "name" : "new York",
    "less" : "charlottesville",
    "city1" : "boston",
    "city2" : "chicago",
    "city3" : "san francisco",
  },
  {
    "name" : "las vegas",
    "less" : "college station",
    "city1" : "atlantic city",
    "city2" : "kansas city",
    "city3" : "philadelphia",
  },
  {
    "name" : "los angeles",
    "less" : "charlottesville",
    "city1" : "san diego",
    "city2" : "new york",
    "city3" : "miami",
  },
  {
    "name" : "new haven",
    "less" : "charlottesville",
    "city1" : "hartford",
    "city2" : "sacramento",
    "city3" : "tampa",
  },
  {
    "name" : "nashville",
    "less" : "columbia",
    "city1" : "kansas city",
    "city2" : "pittsburgh",
    "city3" : "phoenix",
  },
  {
    "name" : "seattle",
    "less" : "charlottesville",
    "city1" : "boston",
    "city2" : "chicago",
    "city3" : "atlanta",
  },
  {
    "name" : "houston",
    "less" : "college station",
    "city1" : "dallas",
    "city2" : "philadelphia",
    "city3" : "phoenix",
  },
  {
    "name" : "north port",
    "less" : "sebastian",
    "city1" : "cape coral",
    "city2" : "providence",
    "city3" : "las vegas",
  },
  {
    "name" : "dallas",
    "less" : "college station",
    "city1" : "atlanta",
    "city2" : "denver",
    "city3" : "chicago",
  },
  {
    "name" : "sacramento",
    "less" : "columbia",
    "city1" : "phoenix",
    "city2" : "kansas city",
    "city3" : "houston",
  },
  {
    "name" : "louis",
    "less" : "bloomigton",
    "city1" : "pittsburgh",
    "city2" : "denver",
    "city3" : "atlanta",
  },
  {
    "name" : "pittsburgh",
    "less" : "iowa city",
    "city1" : "cincinnati",
    "city2" : "phoenix",
    "city3" : "nashville",
  }
]
  export default city;
